### ISSUE TITLE
Home Assistant !

### ISSUE THREAD

**Issue by m-alzahrani** [nicholasrobinson/homebridge-smartcielo#1]
Is there any way to use this plugin in Home Assistant?

**Comment by nicholasrobinson** [comment]
Not directly. 

It appears there is/was a plug-in to allow home ridge control from home assistant:
https://github.com/home-assistant/homebridge-homeassistant

But it would be more efficient to write a new home assistant plugin that uses the underlying driver directly:
https://github.com/nicholasrobinson/node-smartcielo

I found the following article which describes one particular approach of how this may be done:
https://opensource.com/article/18/8/build-thermostat-open-source-tools

Note: The article suggests that the preferred approach using today’s Home Assistant support is to implement the generic thermostat device:
https://www.home-assistant.io/integrations/generic_thermostat/

Note 2: Specific implementation source code for reference designs can be found here:
https://www.home-assistant.io/integrations/
