### ISSUE TITLE
Any trigger in home app turns ON AC, then off 50 seconds later

### ISSUE THREAD

**Issue by vincentanthony** [nicholasrobinson/homebridge-smartcielo#10]
Anyone been able to get this plugin to work? When I turn on the ac in home app, it will turn on the AC and show on Cielo World site. But AC will turn off 50 seconds later. Home App shows the AC is still on. Any trigger on Cielo world isn’t reflected in home app.

**Comment by androolloyd** [comment]
It worked quite well for me originally but I am unsure what happened, perhaps an update on the manufactures api?

**Comment by robertsfeir** [comment]
Just installed for a McCool (SmartHVAC/Ciello) Mini Split. It sends a signal and turns it on, then goes off fairly soon after as a status in home bridge. However when looking at the SmartHVAC app I can see the Mini split is on.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/homebridge-smartcielo/issues/22
