### ISSUE TITLE
Compatibility Issues w/ Multi-Zone Mini Split System 

### ISSUE THREAD

**Issue by paddedboy** [nicholasrobinson/homebridge-smartcielo#11]
I have a Multi-Zone 36K BTU 3 TON MRCOOL Mini-split system. The system has two zones connected (two mini-splits connected to the same condensing unit). When I configure your app, I am unable to control both mini-split units. Your app will only connect to the primary mini-split connected to the A-side of the condensing unit. Remember, I have a multi-zone system capable of supporting up to 4 different zones (I only have two zones connected). 

Can you please make modifications to your app which would allow the control of each mini-split unit connected to a multi-zone system?

**Comment by nicholasrobinson** [comment]
This request/issue is already tracked by https://github.com/nicholasrobinson/homebridge-smartcielo/issues/9 

closing as a duplicate
