### ISSUE TITLE
Supporting Dry Mode

### ISSUE THREAD

**Issue by robertsfeir** [nicholasrobinson/homebridge-smartcielo#14]
Hello. Super appreciate this plugin. I'm wondering if it's possible to add a 4th mode: Dry. Dry mode on a Mr. Cool just turns on the fan to get the room air moving, and that results in dropping the humidity - since it acts as a dehumidifier, as opposed to dropping the temperature. Would be great to have this mode to combine with a hygrometer, and save energy. Thanks.

**Comment by robertsfeir** [comment]
Here are some HTTP requests to trigger dry mode

Request URL: https://home.cielowigle.com/api/device/getmoderules/1663/dry/

The response shows this is a supported mode:
{fanSpeeds: ["auto", "low", "medium", "high"], modes: ["cool", "dry", "fan", "auto", "heat"],…}
defaultTemperature: 78
displayLight: "on:off"
fanSpeeds: ["auto", "low", "medium", "high"]
isDehumid: 0
isDisplayLightInControlScreen: 0
isDisplayLightInSchedule: 0
isDisplaySwingInSchedule: 1
isFaren: 1
isShowSwingTray: 1
lightStates: null
maxTemperature: "86"
minTemperature: "62"
modelrules: "default:default:default"
modes: ["cool", "dry", "fan", "auto", "heat"]
0: "cool"
1: "dry"
2: "fan"
3: "auto"
4: "heat"
swingPositions: ["auto", "pos1", "pos2", "pos3"]
0: "auto"
1: "pos1"
2: "pos2"
3: "pos3"
tempIncrement: 1
uirules: "default:default:default"

Maybe the additional mode is due to the model number or generation (3rd in my case) of the Mr. Cool unit?

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/homebridge-smartcielo/issues/22
