### ISSUE TITLE
Trying to use with cielo breez plus

### ISSUE THREAD

**Issue by cwtufts** [nicholasrobinson/homebridge-smartcielo#15]
Hey, I have been trying to get this to work with my cielo breez plus (same controller as mrcool) but I cannot get it to connect to the device. I’m curious that since the web address has change that it could be causing an issue.

**Comment by ryanfroese** [comment]
I'm having a similar problem, the config wants the "public IP the AC resides at", however that IP does not work. I login to Cielo on their website, but don't know the IP that would go here for that.

**Comment by isaac-webb** [comment]
Hey all,
I took both of @nicholasrobinson's packages, updated them as best I could, and republished them. [`node-mrcool`](https://github.com/isaac-webb/node-mrcool) is the re-implemented library, and [`homebridge-mrcool`](https://github.com/isaac-webb/homebridge-mrcool) is the homebridge plugin. Please feel free to install and let me know how it works (and any bugs you find...!). I only have 3rd gen single zone MrCool units, so I can't guarantee they'll work on the Cielo units, but if you install and let me know, I'd be more than happy to give it a shot. The config public IP you guys are talking about, I believe, is just supposed to be your internet's public IP (it's used as a session identifier in the kinda terrible Cielo API). The API URL did change though, and I've accounted for that in my package.

**Comment by cwtufts** [comment]
@isaac-webb So I finally got around to playing with it again and it's still not working but I do appreciate the try. I'm not sure what else could be done to try and get it to work

**Comment by ryanfroese** [comment]
@isaac-webb I dug in a bit more (though it's been a while now), and I found that the API you are accessing from Cielo either doesn't exist anymore or doesn't work with my Cielo Breeze. I'm not sure, I contacted Cielo and they said, 

> "Thanks for reaching out. Unfortunately we do not offer any API integration at the moment. We have conveyed your suggestion to our tech team. If we release any APIs for third party integration in future, we will surely update you. Currently Cielo Smart controllers are compatible with Amazon Alexa, Google Home Assistant, Samsung SmartThings, Apple Siri shortcuts and IFTTT."

I've been using IFTTT recently, which *kinda* works. I set up my heating/cooling a switches triggered by IFTTT, however changing temp is sadly not possible.

Would love it if there is a way to get this thing working, though no API on Cielo's end is where I got stuck.

**Comment by isaac-webb** [comment]
See [this](https://github.com/isaac-webb/homebridge-mrcool/issues/3) comment I just made. Unfortunately, they've never had a public API, so it takes some manual effort to figure out how to play nicely with their "private" APIs... I'll try and make some progress on this soon, I just haven't had the time since I initially published the plugin to get it to work again after it broke.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/homebridge-smartcielo/issues/22
