### ISSUE TITLE
SmartCielo account linked with google sign in

### ISSUE THREAD

**Issue by txixmx** [nicholasrobinson/homebridge-smartcielo#7]
Love this progress! For me, I log into my minisplit with google sign in. My cielo account profile won't allow me to change it... Not sure the config will work for me since I bounce my login off google. Any future plans to support this? Or should I abandon that account and create new? Thanks!

**Comment by nicholasrobinson** [comment]
@txixmx Apologies for the delayed response. 

This sounds similar to https://github.com/nicholasrobinson/node-smartcielo/issues/6 , do you encounter any specific errors when you attempt to login using your Google credentials? Or is the issue broader than that, i.e. requiring `oauth` support?

Closing this issue. I would suggest you file a request for Google authentication support against the underlying [node-smartcielo](https://github.com/nicholasrobinson/node-smartcielo) wrapper. You may find it easier to debug using the command line tools packaged with the wrapper.
