### ISSUE TITLE
Feature Request: Multiple systems

### ISSUE THREAD

**Issue by forevaclevah** [nicholasrobinson/homebridge-smartcielo#9]
Based on the forum post from this summer, I understand that homebridge-cielo only supports one unit. I am submitting a feature request to support multiple units. 

Thanks!

**Comment by nicholasrobinson** [comment]
The issue comprises two enhancement requests:

1. The underlying [node-smartcielo](https://github.com/nicholasrobinson/node-smartcielo) wrapper must provide a way to address multiple units. This is tracked by: https://github.com/nicholasrobinson/node-smartcielo/issues/4
2. The [homebridge-smartcielo](https://github.com/nicholasrobinson/homebridge-smartcielo) config parser must allow the user to specify which units are intended for control (by device ID or similar), or dynamically create thermostat/ac accessories for each system detected.

This issue will be used to track item 2 above.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/homebridge-smartcielo/issues/22
